### YamlMime:ManagedReference
items:
- uid: Talegen.AspNetCore.Multitenant.Configuration
  commentId: N:Talegen.AspNetCore.Multitenant.Configuration
  id: Talegen.AspNetCore.Multitenant.Configuration
  children:
  - Talegen.AspNetCore.Multitenant.Configuration.TenantSettings
  langs:
  - csharp
  - vb
  name: Talegen.AspNetCore.Multitenant.Configuration
  nameWithType: Talegen.AspNetCore.Multitenant.Configuration
  fullName: Talegen.AspNetCore.Multitenant.Configuration
  type: Namespace
  assemblies:
  - Talegen.AspNetCore.Multitenant
references:
- uid: Talegen.AspNetCore.Multitenant.Configuration.TenantSettings
  commentId: T:Talegen.AspNetCore.Multitenant.Configuration.TenantSettings
  parent: Talegen.AspNetCore.Multitenant.Configuration
  name: TenantSettings
  nameWithType: TenantSettings
  fullName: Talegen.AspNetCore.Multitenant.Configuration.TenantSettings
- uid: Talegen.AspNetCore.Multitenant.Configuration
  commentId: N:Talegen.AspNetCore.Multitenant.Configuration
  name: Talegen.AspNetCore.Multitenant.Configuration
  nameWithType: Talegen.AspNetCore.Multitenant.Configuration
  fullName: Talegen.AspNetCore.Multitenant.Configuration
